import fetch, { Blob } from 'node-fetch'

import IQLQuery from './IQLQuery'

class IQLClient {
	imageServerUrl: string

	/**
	 * Constructs a new IQLClient for interfacing with an IQLServer
	 * @param imageServerUrl The URL the IQLServer is listening on
	 */
	constructor (imageServerUrl: string) {
		this.imageServerUrl = imageServerUrl
	}

	/**
	 * Sends a IQLQuery to the server
	 * @param query The IQLQuery to send to the server
	 * @returns The image generated by the server
	 */
	async send (query: IQLQuery): Promise<Blob> {
		const response = await fetch(this.imageServerUrl, {
			method: 'POST',
			body: JSON.stringify(query),
		})

		const data = await response.blob()

		return data
	}
}

export default IQLClient
